extends:
  - stylelint-config-standard-scss
  - stylelint-config-idiomatic-order

rules:
  # Order selectors by specificity can make Sass more complicated and less readable
  no-descending-specificity: null
  # Bootstrap does not provide any placeholders
  scss/at-extend-no-missing-placeholder: null
  # Disallow redundant nesting selectors (&)
  scss/selector-no-redundant-nesting-selector: true
